### ISSUE TITLE
[Request] Can you make it ViewPager friendly for horizontal swipe

### ISSUE THREAD

**Issue by iRYO400** [martinwithaar/PinchToZoom#1]
Hey, thanks for the lib. It's realy easy to implement! 
I've found that horizontal swiping intercepts by ViewPager. To translate I need to hold vertical swipe, then to horizontal. 
Thanks, again!

**Comment by martinwithaar** [comment]
Please check out the sample app and download it's source code. You'll see that there is a [custom ViewPager ](https://github.com/martinwithaar/PinchToZoom/blob/master/pinchtozoom/src/main/java/com/bogdwellers/pinchtozoom/view/ImageViewPager.java) implementation included in the library that is used in the sample app to solve this exact problem.

**Comment by iRYO400** [comment]
thanks!
