### ISSUE TITLE
doesn't work inside of a scrollview

### ISSUE THREAD

**Issue by huntj88** [martinwithaar/PinchToZoom#3]
is there a fix for this? it might be because of conflicting onTouchListeners. Maybe it's possible that if you pass a reference of the scrollview to your library, you could handle it there?

**Comment by martinwithaar** [comment]
I suspect that image translation is interfering with the scrollview touch semantics. Maybe you could try disabling translation by calling `imageMatrixTouchHandler.setTranslateEnabled(false);` to see if that helps. This would however mean that dragging your zoomed image around is not possible when using a scrollview.
